

version: '3.7'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.29
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    networks:
      - jaeger-tracing
  frontend-jaeger:
    image: im2nguyenhashi/frontend-jaeger
    ports: 
      - 3000:3000
    environment:
      - OTEL_SERVICE_NAME=hashicups-frontend
      - OTEL_TRACE_HOST=jaeger
      - OTEL_TRACE_PORT=14268
      - NEXT_PUBLIC_PUBLIC_API_URL=/
      - NEXT_PUBLIC_FOOTER_FLAG=HashiCups
    networks:
      - jaeger-tracing
    depends_on:
      - jaeger

networks:
  jaeger-tracing: