version: 2
jobs:
  build-react:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: /go/src/github.com/hashicorpdemoapp/frontend

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

      - persist_to_workspace:
          root: /go/src/github.com/hashicorpdemoapp
          paths:
            - frontend

  publish-docker-release:
    docker:
      - image: circleci/golang:1.13
    environment:
      GO111MODULE: "on"
    working_directory: /go/src/github.com/hashicorpdemoapp/product-api-go
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /go/src/github.com/hashicorpdemoapp
      - run:
          name: docker login
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          name: docker build
          command: |
            docker build -t hashicorpdemoapp/product-api:${CIRCLE_TAG} .
      - run:
          name: docker push
          command: |
            docker push hashicorpdemoapp/product-api:${CIRCLE_TAG}
  
  publish-docker-db-release:
    docker:
      - image: circleci/golang:1.13
    environment:
      GO111MODULE: "on"
    working_directory: /go/src/github.com/hashicorpdemoapp/product-api-go
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /go/src/github.com/hashicorpdemoapp
      - run:
          name: docker login
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          name: docker build
          command: |
            cd database && docker build -t hashicorpdemoapp/product-api-db:${CIRCLE_TAG} .
      - run:
          name: docker push
          command: |
            docker push hashicorpdemoapp/product-api-db:${CIRCLE_TAG}

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    working_directory: ~/go/src/github.com/hashicorpdemoapp/product-api-go
    steps:
      - attach_workspace:
          at: ~/go/src/github.com/hashicorpdemoapp
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -replace ${CIRCLE_TAG} ./bin/

workflows:
  version: 2
  build-and-release:
    jobs:
      - build-go:
          filters:
            tags:
              only: /.*/
      - publish-docker-release:
          requires:
            - build-go
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - publish-docker-db-release:
          requires:
            - build-go
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - publish-github-release:
          requires:
            - build-go
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
