version: '3.3'
services:
  product-api1:
    image: 'hashicorpdemoapp/product-api:v0.0.20'
    volumes:
      - type: bind
        source: ./conf.json
        target: /conf.json
    links:
      - 'product-db:product-db'
    ports:
      - '9090:9090'
  product-db:
    image: 'hashicorpdemoapp/product-api-db:v0.0.20'
    ports:
      - '15432:5432'
    environment:
      - POSTGRES_DB=products
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
  payments:
    image: 'hashicorpdemoapp/payments:latest'
    ports:
      - "18000:8080"
