version: '3.3'
services:
  public-api:
    image: 'hashicorpdemoapp/public-api:v0.0.6'
    environment:
      - PRODUCT_API_URI=http://product-api:9090
      - PAYMENT_API_URI=http://payments:8080
    links:
      - 'product-api:product-api'
      - 'payments:payments'
    ports:
      - '8080:8080'
  product-api:
    image: 'hashicorpdemoapp/product-api:v0.0.20'
    volumes:
      - type: bind
        source: ./conf.json
        target: /conf.json
    links:
      - 'product-db:product-db'
    ports:
      - '9090:9090'
  product-db:
    image: 'hashicorpdemoapp/product-api-db:v0.0.20'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=products
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
  payments:
    image: 'hashicorpdemoapp/payments:latest'
